name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r day5/requirements.txt

      - name: Check CSV exists
        run: |
          ls -lb day5/homework_day5/data || true
          find day5/homework_day5/data -printf '%P|\n' || true

      - name: Run pytest
        run: pytest -q day5/homework_day5/tests
